/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdatabase.component;

import appdatabase.entity.Shop;
import appdatabase.format.MaxLenghtString;
import appdatabase.format.Values;
import appdatabase.listentities.ListShops;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Manuel Manzano López
 */
public class ComponentShop extends javax.swing.JPanel {
    private List<Shop> listShops ;
    private Shop shop;
    private int numElementShop;
    
    
    public ComponentShop() {
        initComponents();
        this.setDefault();
        
    }
    
    public ComponentShop(ListShops listShops){
        this();
        this.listShops=listShops.getListShop();
    }
    
    private void setRestrictions(){
        this.jTextFieldName.setDocument(new MaxLenghtString(new Values().MAX15));
        this.jTextFieldEmail.setDocument(new MaxLenghtString(new Values().MAX40));
        this.jTextFieldPhone.setDocument(new MaxLenghtString(new Values().PHONE_NAC_MAX9));
        this.jTextFieldAddress.setDocument(new MaxLenghtString(new Values().MAX40));
    }
    
    public void setElementShop(int numShop){
        this.numElementShop=numShop;
        this.shop=listShops.get(numShop);
        this.setNameShop(this.shop.getNameShop());
        this.setAddress(this.shop.getAddress());
        this.setPhone(this.shop.getPhone());
        this.setEmail(this.shop.getEmail());
        this.repaint();
    }
    
    public void setDefault(){
        this.setNameShop("Elemento no seleccionado");
        this.setAddress("Elemento no seleccionado");
        this.setPhone(0);
        this.setEmail("Elemento no seleccionado");
        this.repaint();
    }
    
    public void setListShops(ListShops listShops){
        this.listShops=listShops.getListShop();
        this.setDefault();
    }
    public String getAddress() {
        return jTextFieldAddress.getText();
    }

    public void setAddress(String Address) {
        this.jTextFieldAddress.setText(Address);
    }

    public String getEmail() {
        return jTextFieldEmail.getText();
    }

    public void setEmail(String Email) {
        this.jTextFieldEmail.setText(Email);
    }

    public String getNameShop() {
        return jTextFieldName.getText();
    }

    public void setNameShop(String Name) {
        this.jTextFieldName.setText(Name);
    }

    public String getPhone() {
        return jTextFieldPhone.getText();
    }

    public void setPhone(int Phone) {
        this.jTextFieldPhone.setText(String.valueOf(Phone));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jToggleButtonSelectModify = new javax.swing.JToggleButton();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel1.setText("Nombre:");

        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setText("Dirección:");

        jTextFieldAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setText("Teléfono:");

        jTextFieldPhone.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("E-mail:");

        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jToggleButtonSelectModify.setText("Consultar");
        jToggleButtonSelectModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSelectModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonSelectModify, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonDelete)
                    .addComponent(jToggleButtonSelectModify))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        listShops.add(numElementShop, shop);
        listShops.remove(numElementShop+1);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jToggleButtonSelectModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSelectModifyActionPerformed
        if(jToggleButtonSelectModify.isSelected()){ 
            this.actionModify();
        }else{
            this.actionSelect();
        }
    }//GEN-LAST:event_jToggleButtonSelectModifyActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        listShops.remove(numElementShop);
        this.setDefault();                
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    private void actionSelect(){
        jToggleButtonSelectModify.setText("Consultar");
        jToggleButtonSelectModify.setSelected(false);
        this.jButtonSave.setEnabled(false);
        this.jButtonDelete.setEnabled(true);
    }
    private void actionModify(){
        jToggleButtonSelectModify.setText("Modificar");
        jToggleButtonSelectModify.setSelected(true);
        this.jButtonSave.setEnabled(true);
        this.jButtonDelete.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JToggleButton jToggleButtonSelectModify;
    // End of variables declaration//GEN-END:variables
}
