/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdatabase.component;

import appdatabase.entity.Employee;
import appdatabase.entity.Shop;
import appdatabase.listentities.ListShops;
import appdatabase.listentities.ListStaff;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Manuel
 */
public class ComponentEmployee extends javax.swing.JPanel {
    private ArrayList<Employee> listEmployee;
    private Employee employee;
    private Shop shop;
    private ArrayList<Shop> listShops;

    /**
     * Creates new form ComponentEmployee
     */
    public ComponentEmployee(){
        initComponents();
        this.setDefault();
        
    }
    public ComponentEmployee(ListStaff listStaff){
        this();
        this.listEmployee=listStaff.getListStaff();
    
    }

    public ArrayList<Employee> getListEmployee() {
        return listEmployee;
    }

    public void setListEmployee(ArrayList<Employee> listEmployee) {
        this.listEmployee = listEmployee;
    }

    public boolean getButtonGroup1() {
        return buttonGroup1.isSelected(jRadioButtonBoss.getModel());
    }

    public void setButtonGroup1(boolean type) {
        this.buttonGroup1.setSelected(jRadioButtonBoss.getModel(), type);
    }

    public Calendar getjDateChooserBornDate() {
        return jDateChooserBornDate.getCalendar();
    }

    public void setBornDate(Calendar jDateChooserBornDate) {
        this.jDateChooserBornDate.setCalendar(jDateChooserBornDate);
    }

    public String getAddress() {
        return jTextFieldAddress.getText();
    }

    public void setAddress(String Address) {
        this.jTextFieldAddress.setText(Address);
    }

    public String getEmail(){
        return jTextFieldEmail.getText();
    }

    public void setEmail(String Email) {
        this.jTextFieldEmail.setText(Email);
    }

    public String getjTextFieldPhone() {
        return jTextFieldPhone.getText();
    }

    public void setPhone(int Phone) {
        this.jTextFieldPhone.setText(String.valueOf(Phone));
    }

    public String getSurname() {
        return jTextFieldSurname.getText();
    }

    public void setSurname(String Surname) {
        this.jTextFieldSurname.setText(Surname);
    }

    public String getNameEmployee() {
        return jTextFieldname.getText();
    }

    public void setname(String nameEmployee) {
        this.jTextFieldname.setText(nameEmployee);
    }
    
    public JComboBox getjComboBoxListShops() {
        return jComboBoxListShops;
    }

    public void setjComboBoxListShops(JComboBox jComboBoxListShops) {
        this.jComboBoxListShops = jComboBoxListShops;
    }

    public Shop getShop() {
        return shop;
    }

    public void setShop(Shop shop) {
        this.shop = shop;
    }

    public ArrayList<Shop> getListShop() {
        return listShops;
    }

    public void setListShop(ListShops listShop) {
        this.listShops = listShop.getListShop();
        ArrayList<Object>tmp=new ArrayList<>();
        for(int i=0; i<listShops.size();i++){
            tmp.add(listShops.get(i).getNameShop());
        }
        this.jComboBoxListShops.setModel(new DefaultComboBoxModel(tmp.toArray()));
        int aux=0;
        while(!(this.shop.equals(this.listShops.get(aux)))){
            aux++;
        }
        this.jComboBoxListShops.setSelectedIndex(aux);
    }
    
    
    public void setEmployee(int employee){
        listEmployee.get(employee);
        this.setName(this.employee.getName());
        this.setSurname(this.employee.getSurname());
        this.setAddress(this.employee.getAddress());
        this.setBornDate(this.employee.getDateBorn());
        this.setEmail(this.employee.getEmail());
        this.jRadioButtonBoss.setEnabled(true);
        this.jRadioButtonEmployee.setEnabled(true);
        this.setButtonGroup1(this.employee.isIsmanager());
        this.setPhone(this.employee.getPhone());
//        this.jComboBoxListShops.setSelectedIndex();
    }
    public void setDefault(){
        this.setName("No hay un emplado selecionado");
        this.setSurname("No hay un emplado selecionado");
        this.setAddress("No hay un emplado selecionado");
        Calendar time= Calendar.getInstance();
        time.setTimeInMillis(System.currentTimeMillis());
        this.setBornDate(time);
        this.setEmail("No hay un empleado selecionado");
        this.jRadioButtonBoss.setEnabled(false);
        this.jRadioButtonEmployee.setEnabled(false);
        this.jComboBoxListShops.setSelectedIndex(-1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserBornDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonBoss = new javax.swing.JRadioButton();
        jRadioButtonEmployee = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxListShops = new javax.swing.JComboBox();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Fecha de Nacimiento:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("E-mail:");

        jLabel7.setText("Jefe/Empleado:");

        buttonGroup1.add(jRadioButtonBoss);
        jRadioButtonBoss.setText("Jefe");

        buttonGroup1.add(jRadioButtonEmployee);
        jRadioButtonEmployee.setText("Empleado");

        jLabel8.setText("Tienda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldname)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldSurname)
                        .addComponent(jLabel3)
                        .addComponent(jDateChooserBornDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldAddress)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldPhone)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonBoss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonEmployee))
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxListShops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jDateChooserBornDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBoss)
                    .addComponent(jRadioButtonEmployee))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxListShops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBoxListShops;
    private com.toedter.calendar.JDateChooser jDateChooserBornDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButtonBoss;
    private javax.swing.JRadioButton jRadioButtonEmployee;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldname;
    // End of variables declaration//GEN-END:variables
}
