/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdatabase.component;

import appdatabase.entity.Product;
import appdatabase.listentities.ListProducts;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.ImageProducer;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Manuel
 */
public class ComponentProduct extends javax.swing.JPanel {
    private ArrayList<Product> listProduct;
    private Product product;
    /**
     * Creates new form ComponentProduct
     */
    public ComponentProduct() {
        initComponents();
    }
    
    public ComponentProduct(ListProducts listProducts){
        this();
        this.listProduct=listProducts.getListProducts();
    }

    public ArrayList<Product> getListProduct() {
        return listProduct;
    }

    public void setListProduct(ListProducts listProduct) {
        this.listProduct = listProduct.getListProducts();
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(int product) {
            this.listProduct.get(product);
    }

    public ImageIcon getPhoto() {
        return new ImageIcon(jLabelPhoto.createImage((ImageProducer) jLabelPhoto.getIcon()));
    }

    public void setPhoto(Image image) {
        this.jLabelPhoto.setIcon(new ImageIcon(image));
    }

    public Color getColor() {
        return jPanelColor.getBackground();
    }

    public void setColor(Color Color) {
        this.jPanelColor.setBackground(Color);
    }

    public String getDescriptions() {
        return jTextAreaDescriptions.getText();
    }

    public void setjTextAreaDescriptions(String Descriptions) {
        this.jTextAreaDescriptions.setText(Descriptions);
    }

    public String getEspcifications() {
        return jTextAreaEspcifications.getText();
    }

    public void setEspcifications(String Espcifications) {
        this.jTextAreaEspcifications.setText(Espcifications);
    }

    public String getBuilder() {
        return jTextFieldBuilder.getText();
    }

    public void setBuilder(String Builder) {
        this.jTextFieldBuilder.setText(Builder);
    }

    public String getModel() {
        return jTextFieldModel.getText();
    }

    public void setModel(String Model) {
        this.jTextFieldModel.setText(Model);
    }

    public String getNameProduct() {
        return jTextFieldName.getText();
    }

    public void setNameProduct(String nameProduct) {
        this.jTextFieldName.setText(nameProduct);
    }

    public double getPrice() {
        return Double.valueOf(jTextFieldPrice.getText());
    }

    public void setPrice(double Price) {
        NumberFormat format= NumberFormat.getCurrencyInstance();
        this.jTextFieldPrice.setText(format.format(Price));
    }

    public String getType() {
        return jTextFieldType.getText();
    }

    public void setType(String Type) {
        this.jTextFieldType.setText(Type);
    }
    public void setDefault(){
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBuilder = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldType = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaEspcifications = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescriptions = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Fabricante:");

        jTextFieldBuilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuilderActionPerformed(evt);
            }
        });

        jLabel3.setText("Modelo:");

        jLabel4.setText("Tipo:");

        jLabel7.setText("Color:");

        jPanelColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jButton1.setText("Color...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fotos:");

        jLabelPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Especificaciones:");

        jTextAreaEspcifications.setColumns(20);
        jTextAreaEspcifications.setRows(5);
        jScrollPane3.setViewportView(jTextAreaEspcifications);

        jTextAreaDescriptions.setColumns(20);
        jTextAreaDescriptions.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDescriptions);

        jLabel10.setText("Descripción:");

        jLabel11.setText("Precio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(100, 100, 100))
                        .addComponent(jLabel4))
                    .addComponent(jTextFieldType)
                    .addComponent(jTextFieldModel)
                    .addComponent(jTextFieldBuilder)
                    .addComponent(jTextFieldName)
                    .addComponent(jTextFieldPrice)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel7)
                    .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBuilder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuilderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuilderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jPanelColor.setBackground(JColorChooser.showDialog(jButton1, "Selector de Color", this.getColor()));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaDescriptions;
    private javax.swing.JTextArea jTextAreaEspcifications;
    private javax.swing.JTextField jTextFieldBuilder;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
