/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdatabase;

import appdatabase.defaulttablerender.Colour;
import appdatabase.defaulttablerender.Dates;
import appdatabase.defaulttablerender.Price;
import appdatabase.listentities.ListProducts;
import appdatabase.listentitiestablemodel.ListShopsTableModel;
import appdatabase.listentities.ListShops;
import appdatabase.listentities.ListStaff;
import appdatabase.listentities.ListStocks;
import appdatabase.listentitiestablemodel.ListProductsTableModel;
import appdatabase.listentitiestablemodel.ListStaffTableModel;
import appdatabase.listentitiestablemodel.ListStockTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Manuel Manzano López
 */
public class main extends javax.swing.JFrame {
    ConectServer conectServer;
    ListShops listadeTiendas = new ListShops("Default");
    ListStaff listadeempleados = new ListStaff("Default");
    ListProducts listadeproductos= new ListProducts("Default");
    ListStocks listadestocks = new ListStocks("Default");
            
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        jTableShops.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableShops.setModel(new ListShopsTableModel(listadeTiendas));
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogManagerConections = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListConnections = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButtonNewConection = new javax.swing.JButton();
        jButtonDeleteConection = new javax.swing.JButton();
        jButtonModifyConection = new javax.swing.JButton();
        jButtonOKConections = new javax.swing.JButton();
        jButtonCancelConections = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jTabbedPanemenuRibbon = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jToolBarRibbon = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanelStatusBar = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableShops = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableStock = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTable = new javax.swing.JList();
        jMenuBarmenu = new javax.swing.JMenuBar();
        jMenuFileExit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuItemRedo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCut = new javax.swing.JMenuItem();
        jMenuItemCopy = new javax.swing.JMenuItem();
        jMenuItemPaste = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuHistory = new javax.swing.JMenu();
        jMenuView = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFullScreen = new javax.swing.JMenuItem();
        jMenuItemWindowsDefault = new javax.swing.JMenuItem();
        jMenuItemWindowsSide = new javax.swing.JMenuItem();
        jMenuSetting = new javax.swing.JMenu();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemManagenConections = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuDataBase = new javax.swing.JMenu();
        jCheckBoxMenuItemOnOffDataBase = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConection = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuConections = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(jListConnections);

        jLabel1.setText("Conexiones:");

        jButtonNewConection.setText("Nueva Conexión...");

        jButtonDeleteConection.setText("Borrar");

        jButtonModifyConection.setText("Modificar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNewConection)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDeleteConection)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModifyConection)))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewConection)
                    .addComponent(jButtonDeleteConection)
                    .addComponent(jButtonModifyConection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonOKConections.setText("Aceptar");
        jButtonOKConections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKConectionsActionPerformed(evt);
            }
        });

        jButtonCancelConections.setText("Cancelar");

        javax.swing.GroupLayout jDialogManagerConectionsLayout = new javax.swing.GroupLayout(jDialogManagerConections.getContentPane());
        jDialogManagerConections.getContentPane().setLayout(jDialogManagerConectionsLayout);
        jDialogManagerConectionsLayout.setHorizontalGroup(
            jDialogManagerConectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogManagerConectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogManagerConectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogManagerConectionsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOKConections)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelConections)))
                .addContainerGap())
        );
        jDialogManagerConectionsLayout.setVerticalGroup(
            jDialogManagerConectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogManagerConectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogManagerConectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelConections)
                    .addComponent(jButtonOKConections))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPanemenuRibbon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPanemenuRibbon.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTabbedPanemenuRibbonMouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPanemenuRibbon.addTab("File", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPanemenuRibbon.addTab("Edit", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPanemenuRibbon.addTab("tab4", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPanemenuRibbon.addTab("tab4", jPanel9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jToolBarRibbon.setFloatable(false);
        jToolBarRibbon.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("jCheckBox1");

        jPanelStatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanelStatusBarLayout = new javax.swing.GroupLayout(jPanelStatusBar);
        jPanelStatusBar.setLayout(jPanelStatusBarLayout);
        jPanelStatusBarLayout.setHorizontalGroup(
            jPanelStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusBarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanelStatusBarLayout.setVerticalGroup(
            jPanelStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
            .addComponent(jSeparator6)
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTableShops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableShops);

        jTabbedPane1.addTab("tab1", jScrollPane2);

        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableEmployee);

        jTabbedPane1.addTab("tab1", jScrollPane5);

        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableProducts);

        jTabbedPane1.addTab("tab1", jScrollPane4);

        jTableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableStock);

        jTabbedPane1.addTab("tab1", jScrollPane6);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jListTable.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tiendas", "Empleados", "Productos", "Stock", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListTable.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTableValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListTable);

        jMenuFileExit.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuFileExit.add(jMenuItem1);

        jMenuBarmenu.add(jMenuFileExit);

        jMenuEdit.setText("Editar");

        jMenuItemUndo.setText("Deshacer");
        jMenuItemUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUndoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemUndo);

        jMenuItemRedo.setText("Rehacer");
        jMenuItemRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRedoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemRedo);
        jMenuEdit.add(jSeparator1);

        jMenuItemCut.setText("Cortar");
        jMenuEdit.add(jMenuItemCut);

        jMenuItemCopy.setText("Copiar");
        jMenuEdit.add(jMenuItemCopy);

        jMenuItemPaste.setText("Pegar");
        jMenuEdit.add(jMenuItemPaste);
        jMenuEdit.add(jSeparator2);

        jMenuHistory.setText("Historial");
        jMenuEdit.add(jMenuHistory);

        jMenuBarmenu.add(jMenuEdit);

        jMenuView.setText("Ver");

        jMenuItem2.setText("jMenuItem2");
        jMenuView.add(jMenuItem2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Barra de Menú");
        jMenuView.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Barra de Estado");
        jMenuView.add(jCheckBoxMenuItem2);
        jMenuView.add(jSeparator7);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Ocultar Barra de Menú");
        jMenuView.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Ocultar Barra de Estado");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenuView.add(jRadioButtonMenuItem2);
        jMenuView.add(jSeparator8);

        jMenuItemFullScreen.setText("Pantalla Completa");
        jMenuItemFullScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFullScreenActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemFullScreen);

        jMenuItemWindowsDefault.setText("Ventana Normal");
        jMenuView.add(jMenuItemWindowsDefault);

        jMenuItemWindowsSide.setText("Ventana Lateral");
        jMenuView.add(jMenuItemWindowsSide);

        jMenuBarmenu.add(jMenuView);

        jMenuSetting.setText("Preferencias");
        jMenuBarmenu.add(jMenuSetting);

        jMenuTools.setText("Herramientas");

        jMenuItemManagenConections.setText("Gestor de Conexiones");
        jMenuTools.add(jMenuItemManagenConections);

        jMenuItem3.setText("jMenuItem3");
        jMenuTools.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenuTools.add(jMenuItem4);

        jMenuBarmenu.add(jMenuTools);

        jMenuDataBase.setText("Base de Datos");

        jCheckBoxMenuItemOnOffDataBase.setSelected(true);
        jCheckBoxMenuItemOnOffDataBase.setText("Conectar/Desconectar");
        jCheckBoxMenuItemOnOffDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemOnOffDataBaseActionPerformed(evt);
            }
        });
        jMenuDataBase.add(jCheckBoxMenuItemOnOffDataBase);
        jMenuDataBase.add(jSeparator3);

        jMenuItemConection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConectionActionPerformed(evt);
            }
        });
        jMenuDataBase.add(jMenuItemConection);
        jMenuDataBase.add(jSeparator4);

        jMenuConections.setText("Conexiones");
        jMenuDataBase.add(jMenuConections);

        jMenuBarmenu.add(jMenuDataBase);

        jMenuHelp.setText("Ayuda");
        jMenuBarmenu.add(jMenuHelp);

        setJMenuBar(jMenuBarmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(640, 640, 640))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToolBarRibbon, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarRibbon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanelStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jToolBarRibbon.isVisible()){
            jToolBarRibbon.setVisible(false);
            jMenuBarmenu.setVisible(true);
            this.repaint();
        }else{
            jToolBarRibbon.setVisible(true);
            jMenuBarmenu.setVisible(false);
            jTabbedPanemenuRibbon.setSize(jToolBarRibbon.getSize());
            this.repaint();
            jTableShops.repaint();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPanemenuRibbonMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTabbedPanemenuRibbonMouseWheelMoved

    }//GEN-LAST:event_jTabbedPanemenuRibbonMouseWheelMoved

    private void jMenuItemRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRedoActionPerformed

    private void jMenuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUndoActionPerformed

    private void jMenuItemConectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConectionActionPerformed

    private void jMenuItemFullScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFullScreenActionPerformed
       this.setExtendedState(MAXIMIZED_BOTH);
       
    }//GEN-LAST:event_jMenuItemFullScreenActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jCheckBoxMenuItemOnOffDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemOnOffDataBaseActionPerformed
       conectServer=new ConectServer(null, null, null, null);
    }//GEN-LAST:event_jCheckBoxMenuItemOnOffDataBaseActionPerformed

    private void jButtonOKConectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKConectionsActionPerformed
        jListConnections.setModel(null);
    }//GEN-LAST:event_jButtonOKConectionsActionPerformed

    private void jListTableValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTableValueChanged
       
        switch(jListTable.getSelectedIndex()){
            case 0:
                jTabbedPane1.setSelectedIndex(0);
                jTableShops.setModel(new ListShopsTableModel(listadeTiendas));
                
                break;
            case 1:
                jTabbedPane1.setSelectedIndex(1);
//                jTableEmployee.setModel(new ListStaffTableModel(listadeempleados));
//                jTableEmployee.getColumnModel().getColumn(3).setCellRenderer(new Dates());
                break;
            case 2:
                jTabbedPane1.setSelectedIndex(2);
                jTableProducts.setModel(new ListProductsTableModel(listadeproductos));
//                jTableProducts.getColumnModel().getColumn(6).setCellRenderer(new Colour());
//                jTableProducts.getColumnModel().getColumn(9).setCellRenderer(new Price());
                break;
            case 3:
                jTabbedPane1.setSelectedIndex(3);
                jTableStock.setModel(new ListStockTableModel(listadestocks));
        
        }
            
            
    }//GEN-LAST:event_jListTableValueChanged

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTabbedPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorAdded

    }//GEN-LAST:event_jTabbedPane1AncestorAdded
    
    
    private void windowsClosing(){
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            
            public void windowsClosing(WindowEvent evt){
                close();
            }
});
    }
    
    private void close(){
        if (JOptionPane.showConfirmDialog(this, "¿Desea salir?",
                "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            
            }else{
                JOptionPane.showMessageDialog(this, "Los datos se perderán.", "Atención", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelConections;
    private javax.swing.JButton jButtonDeleteConection;
    private javax.swing.JButton jButtonModifyConection;
    private javax.swing.JButton jButtonNewConection;
    private javax.swing.JButton jButtonOKConections;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemOnOffDataBase;
    private javax.swing.JDialog jDialogManagerConections;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListConnections;
    private javax.swing.JList jListTable;
    private javax.swing.JMenuBar jMenuBarmenu;
    private javax.swing.JMenu jMenuConections;
    private javax.swing.JMenu jMenuDataBase;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFileExit;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuHistory;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemConection;
    private javax.swing.JMenuItem jMenuItemCopy;
    private javax.swing.JMenuItem jMenuItemCut;
    private javax.swing.JMenuItem jMenuItemFullScreen;
    private javax.swing.JMenuItem jMenuItemManagenConections;
    private javax.swing.JMenuItem jMenuItemPaste;
    private javax.swing.JMenuItem jMenuItemRedo;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JMenuItem jMenuItemWindowsDefault;
    private javax.swing.JMenuItem jMenuItemWindowsSide;
    private javax.swing.JMenu jMenuSetting;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelStatusBar;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPanemenuRibbon;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JTable jTableProducts;
    private javax.swing.JTable jTableShops;
    private javax.swing.JTable jTableStock;
    private javax.swing.JToolBar jToolBarRibbon;
    // End of variables declaration//GEN-END:variables
}
